/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
*/
//Autogenerated VP1 Factory Code Implementation File (Fri Aug 19 13:36:52 CEST 2016)

#include <QtPlugin>
#include "VTI12FaserPlugin/VP1FaserPlugin_VP1AutoFactory.h"
#include "VTI12FaserPlugin/VP1FaserChannel.h"

QStringList VP1FaserPlugin_VP1AutoFactory::channelWidgetsProvided() const
{
  return QStringList()
        << "Faser"
         ;
}

IVP1ChannelWidget * VP1FaserPlugin_VP1AutoFactory::getChannelWidget(const QString & channelwidget)
{
  if (channelwidget == "Faser")
    return new VP1FaserChannel();

  return 0;
}

